config/routes.rb
Makeitsnappy::Application.routes.draw do

  root to: 'questions#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  resources :questions, except: [:new] do 
    resources :answers, only: [:create]
  end

  match '/register', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/your_questions', to: 'questions#your_questions'
  match '/search', to: 'questions#search'
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  attr_accessible :body

  validates :body, presence: true, length: { in: 2..255 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  attr_accessible :body, :solved

  validates :body, presence: true, length: { in: 10..255 }
  validates :solved, inclusion: { in: [true, false]}

  def self.unsolved(params)
  	where(solved: false).paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
  end

  def self.search(params)
  	where("body LIKE ?", "%#{params[:keyword]}%").paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
  attr_accessible :username, :password, :password_confirmation

  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false },
  										 length: { in: 4..12 },
  										 format: { with: /^[a-z][a-z0-9]*$/, message: 'can only contain lowercase letters and numbers' }
	validates :password, length: { in: 4..8 }
	validates :password_confirmation, length: { in: 4..8 }

	def your_questions(params)
		questions.paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	before_filter :auth, only: [:create]

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(params[:answer])
		@answer.user = current_user

		if @answer.save
			flash[:success] = 'Your answer has been posted!'
			redirect_to @question
		else
			@question = Question.find(params[:question_id])
			render 'questions/show'
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method [:current_user, :logged_in?]

  protected

  	def login(user)
  		session[:user_id] = user.id
  	end

  	def current_user
  		current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end

  	def logged_in?
  		!current_user.nil?
  	end

    def auth
      redirect_to login_url, alert: 'You must login to access that page' unless logged_in?
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :auth, only: [:create, :your_questions, :edit, :update]
	
  def index
  	@question = Question.new
    @questions = Question.unsolved(params)
  end

  def create
  	@question = current_user.questions.build(params[:question])
  	if @question.save
  		flash[:success] = 'Your question has been posted!'
  		redirect_to @question
  	else
      @questions = Question.unsolved(params)
  		render 'index'
  	end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def your_questions
    @questions = current_user.your_questions(params)
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])

    if @question.update_attributes(params[:question])
      flash[:success] = 'Your question has been updated!'
      redirect_to @question
    else
      render 'edit'
    end
  end

  def search
    @questions = Question.search(params)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:session][:username])
  	if user && user.authenticate(params[:session][:password])
  		login user
  		flash[:success] = 'You are now logged in!'
  		redirect_to root_url
  	else
  		flash.now[:error] = 'Your username/password combination was incorrect.'
  		render 'new'
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are now logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      login @user
  		flash[:success] = 'Thanks for registering!'
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

	def on_your_questions_page?
		action_name == 'your_questions'
	end

	def display_solved(question)
		(question.solved) ? ' - (Solved) ' : ''
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<li class="well">
	<%= answer.body %> - by <%= answer.user.username.capitalize %>
</li>

app/views/answers/_answer_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
	
	<%= render 'common/form_errors', object: @answer %>

	<p>
		<%= f.label :body, "Answer" %>
		<%= f.text_field :body, class: 'search2' %>
		<%= f.submit "Post Answer", class: 'btn btn-primary' %>
	</p>
<% end %>

app/views/common/_form_errors.html.erb
<% if object.errors.any? %>
	
		<% object.errors.full_messages.each do |message| %>
		<div class="alert alert-error">
			<a class="close" data-dismiss="alert">×</a>
			<p><%= message %></p>
			</div>
		<% end %>
		
<% end %>

app/views/common/_search_form.html.erb
<%= form_tag(search_path, method: 'get') do %>
	<%= text_field_tag :keyword, 'Search', size: '20', id: 'keyword', class: 'search' %>
	<%= submit_tag "Search", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container-fluid">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <%= link_to 'Simple Blog', root_path, class: 'brand' %>
    <div class="nav-collapse collapse">
      <ul class="nav">
        <% if logged_in? %>
          <li><%= link_to "Your Q's", your_questions_path %></li>
          <li><%= link_to "Logout (#{current_user.username})", logout_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Register', register_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
        	<li><%= render 'common/search_form' %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</div>
<hr>
<div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
		<div id="content">
			<%= render 'shared/notifications' %>
			<%= yield %>
	</div><!-- end content -->
      </div><!--/span-->
    </div><!--/row-->



</body>
</html>

app/views/questions/_question.html.erb
<li class='well'>
	<%= link_to truncate(question.body, length: 35), question %> by <%= question.user.username.capitalize %> 

	<% if on_your_questions_page? %>
		<%= display_solved(question) %>- <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-warning' %>
	<% end %>

	- (<%= pluralize(question.answers.count, 'answer') %>)
</li>

app/views/questions/_question_form.html.erb
<%= form_for(@question) do |f| %>
	<%= render 'common/form_errors', object: @question %>

	<p>
		<%= f.label :body, "Question" %><br />
		<%= f.text_field :body, class: 'search2'%>

		<%= f.submit "Ask a Question", class: 'btn btn-primary'%>
	</p>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Your Question</h1>

<%= form_for(@question) do |f| %>
	
	<%= render 'common/form_errors', object: @question %>

	<hr>
	<p>
		<%= f.text_field :body %>
	</p>
	<hr>
	<p>
		<%= f.label :solved %>
		<%= f.check_box :solved %>
	</p>
	<p>
		<%= f.submit "Update", class: 'btn btn-primary' %>
	</p>
<% end %>

app/views/questions/index.html.erb
<div id="ask">
	<h1>Ask a Question</h1>

	<% if logged_in? %>
		<%= render 'question_form' %>
	<% else %>
		<p>Please login to ask or answer questions.</p>
	<% end %>
</div><!-- end ask -->

<div id="questions">
	<h2>Unsolved Questions</h2>

	<% if @questions.any? %>
		<ul>
			<%= render @questions %>
		</ul>
		<%= will_paginate %>
	<% else %>
		<p>No questions have been asked.</p>
	<% end %>
</div><!-- end questions -->

app/views/questions/search.html.erb
<h1>Search Results</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>Nothing found, please try a different search.</p>
<% end %>

app/views/questions/show.html.erb
<h1>
	<%= @question.user.username.capitalize %> asks:
</h1>

<ul>
	<li class='well'><%= @question.body %></li>
</ul>

<div id="answers">
	<h2>Answers</h2>

	<% if @question.answers.any? %>
		<ul>
			<li><%= render @question.answers %></li>
		</ul>
	<% else %>
		<p>This question has not been answered yet.</p>
	<% end %>
</div><!-- end answers -->
<hr>
<div id="post-answer">
	<h2>Answer this Question</h2>

	<% if logged_in? %>
		<%= render 'answers/answer_form' %>
	<% else %>
		<p>Please login to post an answer for this question.</p>
	<% end %>
</div><!-- end post-answer -->

app/views/questions/your_questions.html.erb
<% provide(:title, 'Your Questions') %>
<div class='span12'>
<h1>Your Questions</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>You've not posted any questions yet.</p>
</div>
<% end %>

app/views/shared/_notifications.html.erb
<% [:error, :alert, :success, :info].each do |type| %>

  <% unless flash[type].blank? %>
  
    <div class="alert alert-<%= type %>">
        <a class="close" data-dismiss="alert">×</a>
        <p><%= flash[type] %></p>
    </div>

  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for(@user) do |f| %>
	<%= render 'common/form_errors', object: @user %>

	<p>
		<%= f.label :username %><br />
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation, 'Confirm' %><br />
		<%= f.password_field :password_confirmation %>
	</p>

	<p>
		<%= f.submit "Register" %>
	</p>
<% end %>